library("ggplot2")
pdf("diamondsData.pdf")
dim(diamonds)
names(diamonds)
str(diamonds)
diamonds[1:5,]
summary(diamonds)
hist(diamonds$price, breaks = 100)
pie(table(diamonds$cut))
boxplot(diamonds$price~cut, data=diamonds)
graphics.off()
pdf("diamondsDataScatter.pdf")
with(diamonds, plot(diamonds$carat, diamonds$price, col=diamonds$cut))
graphics.off()
pdf("diamondsDataPairs.pdf")
pairs(diamonds)
graphics.off()